import Head from "next/head";
import Image from "next/image";
import { ArrowUpRightIcon } from "@heroicons/react/24/solid";
import profilePic from "../public/me.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Filippo Brigati</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-xl m-auto px-6 py-4 sm:px-2 sm:py-2">
        <div className="pt-2 sm:pt-20 w-full flex flex-row justify-start items-center">
          <span className="w-fit">
            <Image
              src={profilePic}
              alt="Picture of the author"
              width={100}
              height={100}
              placeholder="blur" // Optional blur-up while loading
              className="rounded-full"
            />
          </span>
          <div className="w-full flex flex-col justify-start items-start ml-5">
            <p className="font-thin text-xl text-[#111111] dark:text-white">Filippo Brigati</p>
            <p className="font-thin text-sm text-[#666666] dark:text-gray-100">
              Computer science student in Italy
            </p>
            <a
              href="https://github.com/filippo-brigati"
              target="_blank"
              rel="noreferrer"
              className="font-thin text-sm text-[#AAAAAA] dark:text-gray-100 hover:underline"
            >
              @filippo-brigati
            </a>
          </div>
        </div>
        <div className="pt-8 sm:pt-12 flex flex-col justify-start items-start w-full">
          <p className="font-thin text-sm text-[#111111] dark:text-white">About</p>
          <p className="font-thin text-sm text-[#666666] dark:text-gray-100 leading-7 pt-2 pl-2 sm:pl-0">
            I am 20 years old guy based in Reggio Emilia. I'm also a student and
            a passionate web developer with a love for code and open-source
            technology. With a background in computer science, I am experienced
            in building and maintaining websites and web applications. In my
            free time, I enjoy exploring the great outdoors through hiking and
            walks in the mountains.
          </p>
          <p className="font-thin text-sm text-[#666666] dark:text-gray-100 leading-7 pt-4 pl-2 sm:pl-0">
            At the moment I'm studing computer science at University of Bologna,
            previously i worked as a Software Developer for an year. Now I'm
            focussed with React and TypeScript but I'm going to learn React
            Native for mobile development.
          </p>
        </div>
        <div className="pt-8 sm:pt-12 flex flex-col justify-start items-start w-full">
          <p className="font-thin text-sm text-[#111111] dark:text-white pb-4 sm:pb-6">
            Side Project
          </p>
          <div className="flex flex-col sm:flex-row justify-start items-start w-full pl-2 sm:pl-0">
            <span className="font-thin text-[#AAAAAA] dark:text-gray-100 text-sm w-full sm:w-1/3 pb-2 sm:pb-0">
              2023
            </span>
            <div className="flex flex-col justify-start items-start w-full sm:w-2/3">
              <div className="flex flex-row justify-end items-start gap-x-1 group hover:cursor-pointer">
                <p className="font-thin text-[#111111] dark:text-white text-sm group-hover:underline">
                  Tsks
                </p>
                <span className="group-hover:underline">
                  <ArrowUpRightIcon className="h-2 w-2 dark:text-gray-100" />
                </span>
              </div>
              <p className="font-thin text-[#AAAAAA] dark:text-gray-100 text-sm">
                This is a simple, user friendly, tasks app. It will be released
                within a few months. (Coming Soon).
              </p>
            </div>
          </div>
          <div className="flex flex-col sm:flex-row justify-start items-start w-full pl-2 sm:pl-0 mt-5">
            <span className="font-thin text-[#AAAAAA] dark:text-gray-100 text-sm w-full sm:w-1/3 pb-2 sm:pb-0">
              2022
            </span>
            <div className="flex flex-col justify-start items-start w-full sm:w-2/3">
              <div className="flex flex-row justify-end items-start gap-x-1 group hover:cursor-pointer">
                <p className="font-thin text-[#111111] dark:text-white text-sm group-hover:underline">
                  Linkly
                </p>
                <span className="group-hover:underline">
                  <ArrowUpRightIcon className="h-2 w-2 dark:text-gray-100" />
                </span>
              </div>
              <p className="font-thin text-[#AAAAAA] dark:text-gray-100 text-sm">
                This is a simple web app made with React and Tailwind that
                generare shortener link of an input.
              </p>
            </div>
          </div>
        </div>
        <div className="pt-8 sm:pt-12 flex flex-col justify-start items-start w-full">
          <p className="font-thin text-sm text-[#111111] dark:text-white pb-4 sm:pb-6">
            Work Experience
          </p>
          <div className="flex flex-col sm:flex-row justify-start items-start w-full pl-2 sm:pl-0">
            <span className="font-thin text-[#AAAAAA] dark:text-gray-100 text-sm w-full sm:w-1/3 pb-2 sm:pb-0">
              2021-2022
            </span>
            <div className="flex flex-col justify-start items-start w-full sm:w-2/3">
              <div className="flex flex-row justify-end items-start gap-x-1 group hover:cursor-pointer">
                <p className="font-thin text-[#111111] dark:text-white text-sm group-hover:underline">
                  Software Developer at GAB Tamagnini
                </p>
                <span className="group-hover:underline">
                  <ArrowUpRightIcon className="h-2 w-2 dark:text-gray-100" />
                </span>
              </div>
              <p className="font-thin text-[#AAAAAA] dark:text-gray-100 text-sm">Italy</p>
            </div>
          </div>
        </div>
        <div className="pt-8 sm:pt-12 flex flex-col justify-start items-start w-full gap-y-3 pb-6">
          <p className="font-thin text-sm text-[#111111] dark:text-white">Contact</p>
          <div className="w-full flex flex-row justify-start items-start">
            <span className="font-thin text-[#AAAAAA] dark:text-gray-100 text-sm w-2/6">
              Instagram
            </span>
            <a
              href="https://www.instagram.com/fillo.brigati/"
              target="_blank"
              rel="noreferrer"
              className="font-thin text-[#111111] dark:text-white text-sm w-4/6 underline"
            >
              fillo.brigati
            </a>
          </div>
          <div className="w-full flex flex-row justify-start items-start">
            <span className="font-thin text-[#AAAAAA] dark:text-gray-100 text-sm w-2/6">
              Twitter
            </span>
            <a
              href="https://twitter.com/brigati_filippo"
              target="_blank"
              rel="noreferrer"
              className="font-thin text-[#111111] dark:text-white text-sm w-4/6 underline"
            >
              brigati_filippo
            </a>
          </div>
          <div className="w-full flex flex-row justify-start items-start">
            <span className="font-thin text-[#AAAAAA] dark:text-gray-100 text-sm w-2/6">
              GitHub
            </span>
            <a
              href="https://github.com/filippo-brigati"
              target="_blank"
              rel="noreferrer"
              className="font-thin text-[#111111] dark:text-white text-sm w-4/6 underline"
            >
              filippo-brigati
            </a>
          </div>
          <div className="w-full flex flex-row justify-start items-start">
            <span className="font-thin text-[#AAAAAA] dark:text-gray-100 text-sm w-2/6">
              Linkedin
            </span>
            <a
              href="https://www.linkedin.com/in/filippo-brigati-6569981b2/"
              target="_blank"
              rel="noreferrer"
              className="font-thin text-[#111111] dark:text-white text-sm w-4/6 underline"
            >
              filippo-brigati
            </a>
          </div>
        </div>
      </div>
    </>
  );
}
